### PR TITLE
Fixes a bug that donwloading a file using wget or curl always fails even when it succeeds.

### LINKED ISSUE #443: "Download failed." even if the file is successfully downloaded.
Regardless of what I'm downloading, I see the error "Download failed."

# Extensions

## First Run

```
===> Downloading from http://pecl.php.net/get/APC-3.1.13.tgz
--2014-12-31 13:02:46--  http://pecl.php.net/get/APC-3.1.13.tgz
Resolving pecl.php.net (pecl.php.net)... 76.75.200.106
Connecting to pecl.php.net (pecl.php.net)|76.75.200.106|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 171591 (168K) [application/octet-stream]
Saving to: ‘/home/kherrera/.phpbrew/distfiles/APC-3.1.13.tgz’

100%[=======================================================================================================================================================================================================================>] 171,591      154KB/s   in 1.1s   

2014-12-31 13:02:47 (154 KB/s) - ‘/home/kherrera/.phpbrew/distfiles/APC-3.1.13.tgz’ saved [171591/171591]

Download failed.
```

## Second Run

```
===> Downloading from http://pecl.php.net/get/APC-3.1.13.tgz
--2014-12-31 13:22:07--  http://pecl.php.net/get/APC-3.1.13.tgz
Resolving pecl.php.net (pecl.php.net)... 76.75.200.106
Connecting to pecl.php.net (pecl.php.net)|76.75.200.106|:80... connected.
HTTP request sent, awaiting response... 200 OK

    The file is already fully retrieved; nothing to do.

Download failed.
```

# Builds

## First Run

```
===> phpbrew will now build 5.6.4
===> Loading and resolving variants...
===> Downloading from http://www.php.net/get/php-5.6.4.tar.bz2/from/this/mirror
--2014-12-31 13:09:41--  http://www.php.net/get/php-5.6.4.tar.bz2/from/this/mirror
Resolving www.php.net (www.php.net)... 72.52.91.14, 2001:470:1:380::3
Connecting to www.php.net (www.php.net)|72.52.91.14|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://php.net/get/php-5.6.4.tar.bz2/from/this/mirror [following]
--2014-12-31 13:09:42--  http://php.net/get/php-5.6.4.tar.bz2/from/this/mirror
Resolving php.net (php.net)... 72.52.91.14, 2001:470:1:380::3
Reusing existing connection to www.php.net:80.
HTTP request sent, awaiting response... 302 Found
Location: http://php.net/distributions/php-5.6.4.tar.bz2 [following]
--2014-12-31 13:09:42--  http://php.net/distributions/php-5.6.4.tar.bz2
Reusing existing connection to www.php.net:80.
HTTP request sent, awaiting response... 200 OK
Length: 13498882 (13M) [application/octet-stream]
Saving to: ‘/home/kherrera/.phpbrew/distfiles/php-5.6.4.tar.bz2’

100%[=======================================================================================================================================================================================================================>] 13,498,882   352KB/s   in 31s    

2014-12-31 13:10:13 (424 KB/s) - ‘/home/kherrera/.phpbrew/distfiles/php-5.6.4.tar.bz2’ saved [13498882/13498882]

Download failed.
```

## Second Run

Forgot to copy and paste the result, but it was successful.

# Information

Here are the permissions for the `.phpbrew` directory:

```
├── [drwxr-xr-x kherrera kherrera]  .phpbrew
│   ├── [-rw-rw-r-- kherrera kherrera]  bashrc
│   ├── [drwxrwxr-x kherrera kherrera]  bin
│   ├── [drwxr-xr-x kherrera kherrera]  build
│   ├── [drwxr-xr-x kherrera kherrera]  distfiles
│   ├── [-rw-rw-r-- kherrera kherrera]  .metadata_never_index
│   ├── [drwxr-xr-x kherrera kherrera]  php
│   ├── [-rw-rw-r-- kherrera kherrera]  phpbrew.fish
│   ├── [-rw-rw-r-- kherrera kherrera]  php-releases.json
│   ├── [drwxr-xr-x kherrera kherrera]  tmp
│   └── [drwxr-xr-x kherrera kherrera]  variants
```

Here is the contents of `.phpbrew/distfiles`:

```
[vm-cin02: kherrera] 13:14:29 distfiles $ pwd
/home/kherrera/.phpbrew/distfiles
[vm-cin02: kherrera] 13:14:30 distfiles $ tree
.
├── APC-3.1.13.tgz
└── php-5.6.4.tar.bz2

0 directories, 5 files
[vm-cin02: kherrera] 13:14:31 distfiles $ 
```

### PR DESCRIPTION
**Pull request by shinnya**
## Purpose
To resolve #443 .

## Changes
Use `Utils::system` method to download a file when wget or curl is used in `UrlDownloader`.

## Effect
Users who don't enable curl extension can download files correctly.

## Tests
Add some test cases for `UrlDownloaderTest`.

### CODE REVIEW

File: src/PhpBrew/Downloader/UrlDownloader.php [hunk 1]
```diff
@@ -53,12 +54,14 @@ public function download($url, $targetFilePath)
 
             // check for wget or curl for downloading the php source archive
             // TODO: use findbin
-            if (exec('command -v wget')) {
-                if(system('wget --no-check-certificate -c -O ' . $targetFilePath . ' ' . $url) !== false){
```
Comment (shinnya) [inline src/PhpBrew/Downloader/UrlDownloader.php]: `system('wget --no-check-certificate -c -O ' . $targetFilePath . ' ' . $url) !== false` must be inverted because `system` function returns `false` only when it fails.

**Comment by c9s** [comment]
Looking good! Thanks!

**Comment by shinnya** [comment]
Thank you for merging!
