### PR TITLE
PHP 8.1 compatibility and fix for PHP7.2 upgrading

### LINKED ISSUE #1245: PHPBrew not compatible with PHP 8.1 when set as system interpreter
### Output

```bash
PHP Deprecated:  Return type of CLIFramework\CommandBase::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php on line 898
PHP Deprecated:  Return type of CLIFramework\CommandBase::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php on line 908
PHP Deprecated:  Return type of CLIFramework\CommandBase::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php on line 903
PHP Deprecated:  Return type of CLIFramework\CommandBase::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php on line 913
PHP Deprecated:  Return type of CLIFramework\CommandBase::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php on line 918
PHP Deprecated:  Return type of Pimple\Container::offsetExists($id) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/pimple/pimple/src/Pimple/Container.php on line 133
PHP Deprecated:  Return type of Pimple\Container::offsetGet($id) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/pimple/pimple/src/Pimple/Container.php on line 98
PHP Deprecated:  Return type of Pimple\Container::offsetSet($id, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/pimple/pimple/src/Pimple/Container.php on line 79
PHP Deprecated:  Return type of Pimple\Container::offsetUnset($id) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/pimple/pimple/src/Pimple/Container.php on line 143
PHP Deprecated:  Return type of GetOptionKit\OptionCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/OptionCollection.php on line 183
PHP Deprecated:  Return type of GetOptionKit\OptionCollection::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/OptionCollection.php on line 178
PHP Deprecated:  Return type of GetOptionKit\OptionResult::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/OptionResult.php on line 42
PHP Deprecated:  Return type of GetOptionKit\OptionResult::offsetExists($name) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/OptionResult.php on line 104
PHP Deprecated:  Return type of GetOptionKit\OptionResult::offsetGet($name) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/OptionResult.php on line 109
PHP Deprecated:  Return type of GetOptionKit\OptionResult::offsetSet($name, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/OptionResult.php on line 99
PHP Deprecated:  Return type of GetOptionKit\OptionResult::offsetUnset($name) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/OptionResult.php on line 114
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 130
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 133
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 136
-bash: /home/trevor/.phpbrew/init: line 3: syntax error near unexpected token `('
-bash: /home/trevor/.phpbrew/init: line 3: `Deprecated: Return type of CLIFramework\CommandBase::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/trevor/.local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php on line 898'
```

### Expected Result

No errors or deprecation warnings

### Command
    phpbrew system php-8.1.0beta2

### Platform

OS: 
    WSL2/Ubuntu 20.04

Running PHP: 
     8.0.9

Installing PHP:
    8.1.0beta2

### LINKED ISSUE #1252: Using and mainaining a fork of phpunit48
Dear phpbrew developers,

for a project of mine I forked phpunit 4.8: https://github.com/xinc-develop/phpunit48

Using the following patch phpunit runs.

    diff --git a/composer.json b/composer.json
    index 39848f39..c9b96ed2 100644
    --- a/composer.json
    +++ b/composer.json
    @@ -21,6 +21,12 @@
         "bin": [
             "bin/phpbrew"
         ],
    +    "repositories": [
    +            {
    +            "type": "vcs",
    +            "url": "https://github.com/xinc-develop/phpunit48"
    +        }
    +    ],
         "require": {
             "php": "^5.3.9||^7.0||^8.0",
             "corneltek/cliframework": "3.0.x-dev#2650a53433854d43b91955e8f967c62ce07869d7",
    @@ -34,7 +40,7 @@
         },
          "require-dev": {
               "php-vcr/php-vcr": "^1.4.5",
    -        "phpunit/phpunit": "^4.8||^5.7||^6.5||^7.5"
    +        "xinc-develop/phpunit48": "dev-master"
         },
          "extra": {
             "branch-alias": {

Maybe there are othe workarounds available to run the test suite?

The phpunit project does not like maintaining a phpunit 4.8 package. https://github.com/sebastianbergmann/phpunit/issues/4841

Is the phpbrew crew interessted in developing phpunit48 further? I would be happy to help with this afford.

---

Running phpunit in fresh checkout of phpbrew with php8.

### Output

./vendor/bin/phpunit 
PHP Fatal error:  Uncaught Error: Call to undefined function each() in /home/ftr/github/phpbrew/vendor/phpunit/phpunit/src/Util/Getopt.php:38
Stack trace:
#0 /home/ftr/github/phpbrew/vendor/phpunit/phpunit/src/TextUI/Command.php(240): PHPUnit_Util_Getopt::getopt()
#1 /home/ftr/github/phpbrew/vendor/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit_TextUI_Command->handleArguments()
#2 /home/ftr/github/phpbrew/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit_TextUI_Command->run()
#3 /home/ftr/github/phpbrew/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in /home/ftr/github/phpbrew/vendor/phpunit/phpunit/src/Util/Getopt.php on line 38

### Expected Result

PHPunit test results

### Command

 ./vendor/bin/phpunit

Running PHP: 

PHP 8.0.13 (cli) (built: Nov 21 2021 22:49:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies

Thanks

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- Drop PHP versions that are lower then `PHP 7.2`.
- Fix the Zsh completion when using the higher `corneltek/getoptionkit` version and remove `corneltek/getoptionkit` conflicts.
  - The referenced commit is [here](https://github.com/c9s/CLIFramework/commit/39bf80e0e4bc2e33747698503b439e8d28587b72).
- Upgrading the `corneltek/cliframework` to the latest `3.x` patch.
- Upgrading the PHPUnit version.
- Closes #1252.
- Closes #1245.
- Fixing the legacy signature implode syntax.
  - The reference is [here](https://www.php.net/manual/en/function.implode.php).

### CODE REVIEW

File: src/PhpBrew/Command/InstallCommand.php [hunk 1]
```diff
@@ -577,7 +577,7 @@ public function execute($version)
         }
 
         if (count($targetPaths)) {
-            $targetConfigPaths = implode($targetPaths, PHP_EOL);
+            $targetConfigPaths = implode(PHP_EOL, $targetPaths);
```
Comment (peter279k) [inline src/PhpBrew/Command/InstallCommand.php:580]: https://www.php.net/manual/en/function.implode.php

File: completion/zsh/_phpbrew [hunk 2]
```diff
@@ -151,7 +151,7 @@ local ret=1
               '--vendor=[Vendor directory name]' \
               '--bootstrap[bootstrap or executable php file]:file:_files' \
               '--executable[make the phar file executable]:boolean' \
-              '(-c --compress)'{-c,--compress}'[compress type\: gz, bz2]::("gz" "bz2")' \
+              '--compress[compress type\: gz, bz2]::("gz" "bz2")' \
```
Comment (peter279k) [inline completion/zsh/_phpbrew:154]: Refer: https://github.com/c9s/CLIFramework/commit/39bf80e0e4bc2e33747698503b439e8d28587b72

**Review by c9s — APPROVED** [review]

File: composer.json [hunk 3]
```diff
@@ -15,30 +15,29 @@
...
     },
     "bin": [
         "bin/phpbrew"
     ],
+    "minimum-stability": "dev",
+    "prefer-stable": true,
     "require": {
-        "php": "^5.3.9||^7.0||^8.0",
-        "corneltek/cliframework": "3.0.x-dev#2650a53433854d43b91955e8f967c62ce07869d7",
+        "php": "^7.2.5||^8.0",
```
Comment (theofidry) [inline composer.json:27]: note that by doing this you are also allowing PHP 8.2, 8.3 & co. which may not be true

Comment (peter279k) [reply composer.json:27]: You're right. Maybe it can change into: `^7.2.5||<=8.1`.
